site_name: Отчет по практической работе
site_description: Практическая работа с применением инструментов концепции "Документация как Код".
site_author: Vasilnyak Nikita
repo_url: https://github.com/NikitaVasil/report_docs-as-code

# theme:
#   name: material
theme:
  name: material

nav:
  - Документация как Код:
      - Описание подхода: '.\\docs\\Description%20of%20the%20approach.md'
      - Практическая часть: '.\\docs\\The%20practical%20part.md'

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - footnotes

copyright: Copyright &copy; 2024 <a href="https://t.me/nikita_vasilnyak">Nikita Vasilnyak</a>.
